- hosts: all
  # vars:
    # docker_compose_version: 1.6.0
    # docker_volumes_version: 1.2

  vars_files:
    - vars.yml

  roles:
    - docker

  pre_tasks:
    - apt:
        name:
          - htop
          - tmux
          - iftop
          - curl
          - vim
      environment: "{{ env | default({}) }}"
