- hosts: all
  vars:
    docker_compose_version: 1.6.0
    docker_volumes_version: 1.2

  vars_files:
    - vars.yml

  roles:
    - docker

  pre_tasks:
    - apt: name={{item}} state=latest
      environment: "{{ env | default({}) }}"
      with_items:
        - htop
        - tmux
        - iftop
        - curl
