- hosts: all
  vars_files:
    - vars.yml

  roles:
    - linuxbrew

  pre_tasks:
    - apt:
        name:
          - htop
          - tmux
          - iftop
          - finger
      environment: "{{ env | default({}) }}"

  tasks:
    - homebrew_tap:
        name: cjbassi/gotop
      become: true
      become_user: linuxbrew
      environment: "{{ env | default({}) }}"

    - homebrew:
        name: gotop
      become: true
      become_user: linuxbrew
      environment: "{{ env | default({}) }}"
