- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - apt: update_cache=yes
      environment: "{{ env | default({}) }}"

    - shell: "which brew > /dev/null && echo found || echo not found"
      register: test_homebrew
      changed_when: false

    - homebrew: update_homebrew=yes
      when: test_homebrew.stdout == "found"
      environment: "{{ env | default({}) }}"

    # - shell: env | grep http_proxy
    #   environment: "{{ env | default({}) }}"